### ISSUE TITLE
Starting the Second Line of a Snippet with a Tab Stop Includes Preceding Whitespace

### ISSUE THREAD

**Issue by TristanSlater** [atom/snippets#234] opened 2017-02-20 00:12 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When creating a snippet with the following two conditions:
- The first characters of the second line is a tab stop
- The second line has the same indent level as the first line

When the snippet is expanded, the tab stop selects the indenting before it.

Things that I've tried:
- Adding a single character or space before the second line tab stop. This causes only the tab stop to be selected.
- Using both the triple quotes and single quotes with `\n` character.
- Several languages including JavaScript, CSS, Python, and C#, so it's not related to a specific language
- With and without tab stop label, i.e., `$1` vs. `${1:Label}`

Here is the code I was trying to create:
```
'.source.js':
  'Extends':
    'prefix': 'ext'
    'body': """
      ${1:ChildClass}.prototype             = Object.create(${2:ParentClass}.prototype);
      ${1:ChildClass}.prototype.constructor = ${1:ChildClass};$0
    """
```

Here is what is produced:
<img width="715" alt="screenshot 2017-02-19 15 42 38" src="https://cloud.githubusercontent.com/assets/1631008/23107919/26807c2a-f6ba-11e6-8ca3-6dbb3b21afe2.png">

Here is what I would like to see (and I think makes more sense):
<img width="705" alt="screenshot 2017-02-19 15 45 18" src="https://cloud.githubusercontent.com/assets/1631008/23107960/70dbe69c-f6ba-11e6-919d-e34b8fb9f293.png">

### Steps to Reproduce

1. Create a new snippet with anything on the first line
2. Start a second line of the snippet at the same indent level as the first line
3. Create a tab stop as the *first* text on the second line
4. Expand the snippet in the appropriate source file (again, only tried JavaScript)

**Expected behavior:** Only the tab stop should be selected

**Actual behavior:** Tab stop and whitespace preceding it is selected

**Reproduces how often:** Every time

### Versions

Atom    : 1.14.3
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

macOS Sierra (Version 10.12.3)

### Additional Information

I can't think of anything.

**Comment by 50Wliu** [comment] 2017-02-20 02:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #140. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-02-20 02:15 UTC

**Comment by TristanSlater** [comment] 2017-02-20 02:40
Searched high and low and couldn't find this! Sorry for not catching this.
