### ISSUE TITLE
$n at the beginning of a line selects preceding spaces

### ISSUE THREAD

**Issue by esdoppio** [atom/snippets#205] opened 2016-05-22 09:57 UTC
Say you have created a snippet with a `$n` at the beginning of a line (no spaces before it), as shown below. Then in a file, at a certain level of indention, when you try to expand that snippet, besides moving the cursor to the specified position, the spaces before it is selected.

You can also reproduce the problem in other types of files.

**Reproduction Steps:**

0. Launch Atom.

1. Put this in the `snippets.cson`:

  ```cson
  '.source.gfm':
    'Ruby sinppet':
      'prefix': 'rb'
      'body': """
        ```Ruby
        $1
        ```
      """
  ```

2. Create a new `test.md` in Atom.

3. In the pane of `test.md`, hit <kbd>Tab</kbd> once (to create a level of indentation), then enter `rb`, hit <kbd>Tab</kbd> again.

**Expected behavior:**

I should have

    ```Ruby
    
    ```

with the cursor at coordinate 2:3, and nothing selected.

**Observed behavior:**

I have

    ```Ruby
    
    ```

with the cursor at coordinate 2:3, and the spaces before that coordinate on the second row selected.

**Atom version:** 1.7.3
**OS and version:** OS X 10.11.5

**Additional information:**

* Problem can be reproduced in safe mode: Yes
* Problem can be reliably reproduced, doesn't happen randomly: Yes
* Problem happens with all files and projects, not only some files or projects: Yes

**Comment by scottmcpherson** [comment] 2016-07-20 09:24
+1 Same issue here accept my snippet has a default value that it's selecting, and it's selecting the preceding white space. 

```
# Python
'.source.python':
  'Docstring':
    'prefix': 'ds'
    'body': """
    '''${1:A description: Tell this function what to do}

    Keyword arguments:
    ${2:arg1} -- ${3:description} ${4:(default ${5:0})}

    Returns: ${6:string}

    '''
    """
```

So when I hit tab to go to `${2:arg1}`, it selects all the preceding white space. When I start typing, it moves my indentation all the way to the right of the editor instead of honoring the indentation.

**Comment by 50Wliu** [comment] 2016-07-20 13:52
This is a duplicate of #140 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-07-20 13:52 UTC
Labels: bug
