### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

### ISSUE THREAD

**Issue by drhayes** [atom/snippets#103] opened 2015-01-28 20:10 UTC
Steps:

1. Type `Object.keys(templates).forEach(f);`
2. Put the cursor after the `f` inside the forEach().
3. Press <kbd>Tab</kbd> because you have a JS snippet that expands to an anonymous function.
4. :boom:

Let me know if you need more information from me!

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.70.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScopeDescriptor' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:375

TypeError: Cannot read property 'getScopeDescriptor' of undefined
  at Object.module.exports.getSnippets (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:375:38)
  at Object.module.exports.snippetToExpandUnderCursor (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:383:23)
  at atom-text-editor.subscriptions.add.atom.commands.add.snippets:expand (/Applications/Atom.app/Contents/Resources/app/node_modules/snippets/lib/snippets.js:46:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  2x -0:13.1 core:move-left (atom-text-editor.editor.is-focused)
     -0:12.6 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.7 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.5 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -0:11.3 core:move-left (atom-text-editor.editor.is-focused)
     -0:11.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.9 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.9 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.7 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.7 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.5 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.5 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.3 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:01.3 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.5 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:00.5 snippets:expand (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "bookmarks",
      "dash",
      "deprecation-cop",
      "jumpy"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-ocean-dark-spacegray"
    ],
    "projectHome": "/Users/drhayes/src"
  }
}
```

### Installed Packages

```coffee
# User
atom-impactjs, v0.0.0
base16-ocean-dark-spacegray, v0.9.0
color-picker, v1.4.4
emmet, v2.3.2
file-icons, v1.4.8
highlight-line, v0.9.3
language-aspx, v0.2.0
language-csharp, v0.3.0
language-ejs, v0.1.0
language-mustache, v0.11.0
mocha, v0.0.5
pretty-json, v0.3.2
visual-bell, v0.9.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment] 2015-04-30 22:42
Sorry for the delay is commenting on this but I'm not able to reproduce using your reproduction steps, is this still something you are seeing in Atom?

**Comment by drhayes** [comment] 2015-05-02 00:28
Wow! Haven't seen it for a while but I've been using Sublime lately.

**Comment by izuzak** [comment] 2015-09-09 17:06
Seems like this was fixed in the meantime -- I can't reproduce this anymore. @drhayes if you notice this again -- please let us know. I'm closing this for now. :v:

**Closed by izuzak** 2015-09-09 17:06 UTC
Labels: more-information-needed, needs-reproduction, uncaught-exception
