### ISSUE TITLE
Over selecting

### ISSUE THREAD

**Issue by steveoh** [atom/snippets#149] opened 2015-06-03 14:26 UTC
I am porting some sublime snippets.

```cson
  'create property':
    'prefix': 'objprop'
    'body': """
 // ${1:property name}: ${2:type}
 // summary:
 //      ${3:description}
 ${1:property name}: ${4: null},$5
"""
```
causes the snippet to expand with all of the whitespace indention selected for $1.

![image](https://cloud.githubusercontent.com/assets/325813/7962321/f602f9b2-09c9-11e5-8fac-046119453e09.png)

If i add a space before `  ${1:property name}: ${4: null},$5`, then the selection is correct but the code is malformed. 

Is this a problem on my part?

**Comment by nathanbuchar** [comment] 2015-06-04 06:50
I opened an issue regarding this same behavior about 15 days ago (#140) :smile: I'll make a note for your case as well

**Comment by mnquintana** [comment] 2015-06-04 11:41
Thanks for the report! This does look like a duplicate of #140, so let's continue the conversation there.

**Closed by mnquintana** 2015-06-04 11:41 UTC
