### ISSUE TITLE
Wrong placeholder selection for two adjacent placeholders

### ISSUE THREAD

**Issue by nerdgore** [atom/snippets#210] opened 2016-08-11 12:35 UTC
I tried creating a snippet that lets you remove parts selectively and got this IMO wrong behaviour.

### Current Behaviour

Defining the snippet like this causes placeholder `$2` to select the wrong character range if I edit placeholder `$1`. It does not matter if the length of the placeholder changes.
```cson
'New broken call':
    'prefix': 'callb'
    'body': '{call .${1:funcName}${2: data="${3:all}"}${4: /}}$0'
```

![screen shot 2016-08-11 at 14 21 40](https://cloud.githubusercontent.com/assets/1582533/17588471/8c3f950a-5fcf-11e6-906b-943042a24a80.png)

### Expected Behaviour

If I add a space between `$1` and `$2` the selection works as expected.
```cson
'New call':
    'prefix': 'call'
    'body': '{call .${1:funcName} ${2:data="${3:all}"}${4: /}}$0'
```

![screen shot 2016-08-11 at 14 22 19](https://cloud.githubusercontent.com/assets/1582533/17588608/843370ec-5fd0-11e6-9f03-b65af8b79827.png)

To replicate the issue, you can check out my fork of the [atom-soy][fork] package, which includes both snippets.

I am using atom 1.9.8, all packages are up to date.

[fork]: https://github.com/nerdgore/atom-soy/tree/more-snippets

**Comment by lee-dohm** [comment] 2016-08-11 22:53
This is a duplicate of https://github.com/atom/text-document/issues/15. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-08-11 22:53 UTC
Labels: bug
