### ISSUE TITLE
Provide a options to set the min word length of snippets. 

### ISSUE THREAD

**Issue by NanerLee** [atom/snippets#227] opened 2016-12-22 06:46 UTC
like the autocomplete-plus package.

**Comment by lee-dohm** [comment] 2016-12-23 22:33
Can you give some more details on what you're asking for? As this issue stands right now, there isn't enough information to determine what to do.

**Comment by NanerLee** [comment] 2016-12-24 08:40
Oh, sorry, I spelt the word .
It should be *'min'*, not *'mini'*.
If you are still puzzled, please see below.

For example:

when i press 'i' key, it will show me:
![2016-12-24 16-30-09](https://cloud.githubusercontent.com/assets/16791509/21466073/4491eb86-c9f6-11e6-8b31-0c453b11c377.png)

but these snippets always bore me.
so i want set the min length of word.
For example, i set the min length to 2. Then when I press 'i' and 'f', it will show me some snippets.

**Comment by hpfdf** [comment] 2017-03-12 17:37
+1
one letter completion makes the whole snippets feature unscalable. Adding an option like 'minLength' would be great.

`  'cerr':
    'prefix': 'cerr'
    'minLength': 2
    'body': 'cerr << $1 << endl;'

  'cin':
    'prefix': 'cin'
    'minLength': 2
    'body': 'cin >> $1;'

  'cout':
    'prefix': 'cout'
    'minLength': 2
    'body': 'cout << $1 << endl;'`

**Comment by lee-dohm** [comment] 2017-03-13 19:18
Thank you for your submission!

We noticed that this is a duplicate of https://github.com/atom/autocomplete-snippets/issues/75. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by lee-dohm** 2017-03-13 19:18 UTC
